theme: jekyll-theme-minimal
title: ADA Template Website
description: TheDataDreamTeam GeoWiki Project
show_downloads: True
navigation:
  - title: GeoWiki
    url: /
  - title: Example
    url: example
